### ISSUE TITLE
More Info || Documentation

### ISSUE THREAD

**Issue by beemsync** [Alumniminium/Yi#1]
I can't even take my breath after seeing the code!  WOW!

Your code lots perfect, there's too much to learn from it, I may spend around a year of two just for analyzing it.

Thank you so much for sharing this.

I was wounding if there's more info about your project or docs.

What client version does this source was built for?
Why is it so different, you used a totally new concept from everyone else?
Why did you build it?

**Comment by Alumniminium** [comment]
If you think that's good code, you have no idea what you're talking about
